import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
    initial: 'en',
    save: process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('en').create({
            button_enter: 'Enter',
            button_exit: 'Exit',
            button_back: 'Back',
            button_leave: 'Leaving the call',
            button_accept: 'Take the call',
            button_map: 'Show on map',
            text_search: 'search',
            text_called: 'Called',
            text_units: 'Units on the scene',
            text_scene: 'on scene',
            text_call: 'Call',

            cad_name: 'POLICE CAD',
            cad_fullname: 'Computer-Aided Dispatching',
            cad_slogan: 'TO PROTECT AND TO SERVE',
            cad_loading: 'Loading',

            main_button_1: 'Main panel',
            main_button_2: 'Calls',
            main_button_3: 'List of residents',
            main_button_4: 'List of vehicles',
            main_button_5: 'State Laws',
            main_button_6: '10-codes',
            main_button_7: 'Management',
            main_button_panic: 'Panic button',

            title_status_1: 'On shift',
            title_status_2: 'On Call',
            title_status_3: 'Busy',
            title_status_4: 'Off shift',

            p1_title_0: 'Active panic button',
            p1_title_1: 'Shift workers',
            p1_title_2: 'Patrol officers',
            p1_title_3: 'People Wanted',
            p1_title_4: 'Wanted cars',

            p1_leave: 'Leave',
            p1_patrol: 'patrol',
            p1_not_selected: 'Not selected',

            p3_birthdate: 'Date of birth',
            p3_gender: 'Gender',
            p3_phone: 'Phone',
            p3_database: 'Database №',
            p3_status: 'Status',
            p3_vehicles: 'Citizen vehicles',
            p3_ticket: 'Write a ticket',
            p3_tickets: 'Citizen penalties',
            p3_author: 'Author',
            p3_date: 'Date',
            p3_reason: 'Reason',
            p3_amount: 'Sum',
            p3_time: 'Time',
            p3_paid: 'Paid',
            p3_officer: "Officer's name: ",
            p3_name: 'Intruder: ',
            p3_date2: 'Date: ',
            p3_violations: 'List of violations',
            p3_short: 'min',
            p3_amount2: 'Amount',
            p3_add: 'Add',
            p3_write: 'Issue a ticket',
            p3_delete: 'Del',
            p3_close: 'Close',

            p4_owner: 'Owner',
            p4_number: 'Owner number',
            p4_database: 'Database №',
            p4_status: 'Status',

            p5_text: 'Text',
            p5_time: 'Time',
            p5_penalty: 'Penalty',

            p7_name : 'Employee data',
            p7_officer: "Officer's name: ",
            p7_rank: 'Rank: ',
            p7_callsign: 'Call sign: ',
            p7_fire: 'Fire',
            p7_close: 'Close',
            p7_change: 'Change',
            p7_sure: 'Are you sure?',
            p7_cancel: 'Cancel',

            p8_name: 'Upload a photo',
            p8_close: 'Close',
            p8_link: 'Link to photo',
            p8_save: 'Save',
        }),
        new MLanguage('ru').create({
            button_enter: 'Войти',
            button_exit: 'Выйти',
            button_back: 'Назад',
            button_leave: 'Покинуть вызов',
            button_accept: 'Принять вызов',
            button_map: 'Показать на карте',
            text_search: 'поиск',
            text_called: 'Вызывавший',
            text_units: 'Юниты на сцене',
            text_scene: 'На сцене',
            text_call: 'Вызов',

            cad_name: 'POLICE CAD',
            cad_fullname: 'Computer-Aided Dispatching',
            cad_slogan: 'TO PROTECT AND TO SERVE',
            cad_loading: 'Загрузка',

            main_button_1: 'Основная панель',
            main_button_2: 'Вызовы',
            main_button_3: 'База жителей',
            main_button_4: 'База автомобилей',
            main_button_5: 'Законы штата',
            main_button_6: '10-коды',
            main_button_7: 'Управление',
            main_button_panic: 'Кнопка паники',

            title_status_1: 'На смене',
            title_status_2: 'На вызове',
            title_status_3: 'Занят',
            title_status_4: 'Вне смены',

            p1_title_0: 'Активный красный код',
            p1_title_1: 'Сотрудники на смене',
            p1_title_2: 'Сотруники в патруле',
            p1_title_3: 'Люди в розыске',
            p1_title_4: 'Машины в розыске',

            p1_leave: 'Покинуть',
            p1_patrol: 'патруль',
            p1_not_selected: 'Не выбрано',

            p3_birthdate: 'Дата рождения',
            p3_gender: 'Пол',
            p3_phone: 'Телефон',
            p3_database: 'Запись в БД',
            p3_status: 'Статус',
            p3_vehicles: 'Автомобили гражданина',
            p3_ticket: 'Выписать штраф',
            p3_tickets: 'Штрафы гражданина',
            p3_author: 'Выдал',
            p3_date: 'Дата',
            p3_reason: 'Причина',
            p3_amount: 'Сумма',
            p3_time: 'Срок',
            p3_paid: 'Плата',
            p3_officer: "Имя офицера: ",
            p3_name: 'Нарушитель: ',
            p3_date2: 'Дата: ',
            p3_violations: 'Список нарушений',
            p3_short: 'мин',
            p3_amount2: 'Сумма',
            p3_add: 'Добавить',
            p3_write: 'Выписать штраф',
            p3_delete: 'Удалить',
            p3_close: 'Закрыть',

            p4_owner: 'Владелец',
            p4_number: 'Номер владельца',
            p4_database: 'Запись в БД',
            p4_status: 'Статус',

            p5_text: 'Текст',
            p5_time: 'Срок',
            p5_penalty: 'Штраф',

            p7_name : 'Данные сотрудника',
            p7_officer: "Имя офицера: ",
            p7_rank: 'Звание: ',
            p7_callsign: 'Позывной: ',
            p7_fire: 'Уволить',
            p7_close: 'Закрыть',
            p7_change: 'Изменить',
            p7_sure: 'Вы уверены?',
            p7_cancel: 'Отменить',

            p8_name: 'Загрузить фотографию',
            p8_close: 'Закрыть',
            p8_link: 'Ссылка на фотографию',
            p8_save: 'Сохранить',
        })
    ]
})